version: "3.8"
services:
  db:
    image: mysql:8.0.27
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: go_scraping_dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: go-scraping-user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - scraping
  cli:
    image: mysql:8.0.27
    networks:
      - scraping
    command: mysql -hdb -uroot -proot go_scraping_dev
networks:
  scraping:
    driver: bridge
